CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email_address VARCHAR(128) UNIQUE NOT NULL,
  password_hash VARCHAR(180) NOT NULL,
  two_factor_secret VARCHAR(256) NOT NULL,
  system_role_id INT NOT NULL,
  deactivated_at TIMESTAMP
);

CREATE TABLE teams (
  team_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name VARCHAR(32) NOT NULL,
  team_description VARCHAR(128)
);

CREATE TABLE members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  team_id INT NOT NULL,
  team_role_id INT NOT NULL,
  removed_at TIMESTAMP
);

CREATE TABLE team_roles (
  team_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_role_name VARCHAR(16) NOT NULL
);

CREATE TABLE system_roles (
  system_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_role_name VARCHAR(32) NOT NULL
);

CREATE TABLE tasks (
  task_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name VARCHAR(32) NOT NULL,
  task_description VARCHAR(256),
  team_id INT NOT NULL,
  status_id INT NOT NULL,
  priority_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP,
  member_id INT
);

CREATE TABLE statuses (
  status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_name VARCHAR(16) NOT NULL
);

CREATE TABLE priorities (
  priority_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  priority_name VARCHAR(16) NOT NULL
);

CREATE TABLE join_requests (
  request_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id INT NOT NULL,
  user_id INT NOT NULL,
  request_status INT NOT NULL,
  requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE request_statuses (
  request_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  request_status_name VARCHAR(16) NOT NULL
);

ALTER TABLE users ADD FOREIGN KEY (system_role_id) REFERENCES system_roles (system_role_id);

ALTER TABLE members ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE members ADD FOREIGN KEY (team_id) REFERENCES teams (team_id);

ALTER TABLE members ADD FOREIGN KEY (team_role_id) REFERENCES team_roles (team_role_id);

ALTER TABLE tasks ADD FOREIGN KEY (team_id) REFERENCES teams (team_id);

ALTER TABLE tasks ADD FOREIGN KEY (status_id) REFERENCES statuses (status_id);

ALTER TABLE tasks ADD FOREIGN KEY (priority_id) REFERENCES priorities (priority_id);

ALTER TABLE tasks ADD FOREIGN KEY (member_id) REFERENCES members (member_id);

ALTER TABLE join_requests ADD FOREIGN KEY (team_id) REFERENCES teams (team_id);

ALTER TABLE join_requests ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE join_requests ADD FOREIGN KEY (request_status) REFERENCES request_statuses (request_status_id);
